project:
  type: book
  output-dir: docs

book:
  title: "Differential Equations in Mathematical Ecology"
  author: "James Watmough"
  event-title: "University of New Brunswick"
  date: last-modified
  date-format: "YYYY MMMM DD"
  chapters:
    - index.qmd
    - M3503-lec01-ODEintro.qmd
    - ode-intro-geom.qmd
    - M3503-lec02-Systems.qmd
    - M3503-lec03-SecondOrderODE.qmd
    - M3503-lec04-LaplaceTransforms.qmd
    - M3503-lec05-FourierSeries.qmd
    - references.qmd

bibliography: dynamical_systems.bib
tbl-cap-location: bottom

execute:
  freeze: auto
  cache: true

format:
  html:
    code-fold: true
    code-summary: "Show the code"
    theme: cosmo
  pdf:
    documentclass: lecturenotes-md
