---
author: James  Watmough
date: "`r Sys.Date()`"
---

{{< include texmacros.qmd >}}


# Fourier Series {#sec-fourier}

## Vectors

## Inner Products

An inner product is an abstraction of the of a scalar projection of one vector onto another.   In Euclidian spaces it most often takes the form of a dot product. 
An inner product allows us to break vectors into orthogonal components and base approximations on projections.  This in turn implies that there will be a best approximation.  We'll use this to approximate complex functions by sums of simpler functions, like polynomials, sines, and cosines.  Approximating a function, or signal, by a sum of sines and cosines effectively breaks down the function into its component frequencies.

::: {#def-innerprod}

An ***inner product*** on a vector space $V$ is a function that assigns
a scalar $\ip{x}{y}$  to each pair, $(x,y)$, of vectors 
 in $V$ and satisfies the following conditions:

1. $\ip{y}{x} = \overline{\ip{x}{y}}$  (conjugate symmetric);
2. $\ip{x}{x} \ge 0$, with equality if and only if $x=0$ (positive definite);
3. $\ip{a w + b x}{y} = a\ip{x}{y} + b\ip{x}{y}$ for all $w$, $x$ and $y$ in $V$ and scalars $a$ and $b$ (bilinear).

:::

::: {.callout-note}
In a real vector space,  the first axiom reduces to a straightforward symmetry: $\ip{x}{y} = \ip{y}{x}$.
:::

::: {.callout-warning}

The notation for inner products varies depending on the application. That's ok, so does the notation for multiplication.

:::

## The usual Fourier Series for $f$


## A more general view of Fourier Series

Suppose $f$ is a piecewise continuous function defined on an interval $[-l,l]$.  
Further, suppose the set of function $\{\phi_0,\phi_1,\phi_2,\dots\}$ is orthogonal
with respect to some given inner product.  Then the fourier series for $f$ with respect
to this set is 
$\displaystyle\sum_{m=0}^\infty c_m \phi_m(x)$
with $c_m = \dfrac{\ip{f}{\phi_m}}{\ip{\phi_m}{\phi_m}}$.

The usual fourier series for $f$ is obtained when 
$\phi_n(x) = \begin{cases}    1 & m=0, \\    \cos(\frac{m\pi x}{2l}) & \text{$m$ even and positive} \\ \sin(\frac{(m+1)\pi x}{2l}) & \text{$m$ odd}  \end{cases}$
and the inner product of two functions, $u$ and $v$, is defined as 
$\ip{u}{v} = \int_{-l}^{l} u(x) v(x) \, dx$.

