---
author: James  Watmough
date: "`r Sys.Date()`"
---

{{< include texmacros.qmd >}}

# First order differential equations {#sec-1storder}

The [OpenStax Calculus][] text covers most of the material we need for first order scalar[^systems] differential equations.  You should have covered all (or at least most) of OpenStax Calculus Volume 1 Chapter 4 in Math 1013.
More specifically,  you should be familiar with viewing a differential equation as a direction field (or vector field) @sec-direction-field.
You should also master the two simplest solution tricks for first order equations: separable first order equations, and linear first order equations.
These require nothing more than a basic mastery of integration.

[^systems]: By *scalar* I just mean a single equation.  We will also look at systems of first order ODEs later in the course (see @sec-systems).

[OpenStax Calculus]: https://openstax.org/books/calculus-volume-2/pages/4-introduction

## Direction fields {#sec-direction-field}

A solution to a first order differential equation, $y' = f(x,y)$, is a function, $y(x)$, whose slope at $x$ is $f(x,y)$.  One way to visualize this is to view $f$ as a *direction field*.  That is, $f$ assigns a slope, or direction, to every point in the $x$-$y$ plane.  The figure below shows the direction field $f:(x,y)\to 2x -1 - 3y$.

```{python}
from matplotlib.pyplot import cm
import matplotlib.pyplot as plt
import numpy as np

nx, ny = .3, .3
x = np.arange(1, 4, nx)
y = np.arange(0, 2, ny)
X, Y = np.meshgrid(x, y)

dy = 2*X -1 - 3*Y
dx = np.ones(dy.shape)

plot2 = plt.figure()
plt.quiver(X, Y, dx, dy, 
           color='Teal', 
           headlength=0, headwidth=1)

plt.title('Direction Field')
plt.show
```

## first order separable equations {#sec-separable}

A first order linear differential equation of the form $\frac{dy}{dt} = f(y)g(t)$
is said to be separable.  It can be solved by a single integration step.
\begin{align*}
  \frac{dy}{dt} &= f(y)g(t) \\
  \frac{1}{f(y)}\frac{dy}{dt} &= g(t) \\
  \int \frac{1}{f(y)}\frac{dy}{dt}\,dt &= \int g(t)\,dt + C \\
  \int \frac{1}{f(y)}\,dy &= \int g(t)\,dt + C 
\end{align*}

::: {#exm-Separable-1}

Find the general solution to the differential equation $\frac{dy}{dt} = ry\cos(t)$.

Separating variables and integrating leads to 
\begin{align}
	\int \frac{1}{y}\,dy &= \int r\cos(t)\,dt +C \\
	\log |y| &= r\sin t  + C \\
	y(t) &= \pm\exp(C+r\sin t ) 
\end{align}
The solution is usually given in the form $y(t) = y_0e^{r\sin(t)}$.
Since $C$ is an arbitrary constant, $y_0 = \pm e^C$ is also arbitrary.
:::

::: {.callout-note}
Since we divide by $y$ on our first step in this example, we must assume $y\ne0$.
However, it is easy to see by inspection that $y=0$ is also a solution to the equation.   
Hence,  we can express the general solution as $y(t) = y_0\exp(r\sin t)$ where $y_0$ can be any real number.
:::

::: {#exm-Separable-2}
  Find the general solution to the differential equation $\frac{dy}{dx} = \frac{6x^2}{2y+\cos y}$.

  Separating variables and integrating leads to 
\begin{align}
  \int (2y+\cos y)\,dy&= \int 6x^2 \, dx + C \\
  y^2+\sin y &= 2x^3  + C
\end{align}
In this case, we are not able to solve for $y$ as a function of $x$.  We are left with $y$ defined implicitly as a function of $x$.
:::

Despite not being able to find an analytic expression for $y$ as a function of $x$ in this example, we can still make nice plots of the solutions.  The trick is to notice that we can find the inverse of the solution. Several solutions are shown in @fig-separable-2

```{python}
#| label: fig-separable-2
#| fig-cap: "Sample solutions for @exm-Separable-2"

import matplotlib.pyplot as plt
import numpy as np

def inversesoln(y,c): return( np.cbrt((y*y+np.sin(y))/2 - c/2) )
y = np.linspace(-np.pi,np.pi,100)
for c in np.arange(-1.2,1.2,.2):
  plt.plot(inversesoln(y,c),y)

plt.xlabel('x')
plt.ylabel('y')
plt.show()
```

::: {#exm-Separable-3}
  Solve the differential equation $\frac{dy}{dx} = \frac{x^2}{y^2}$.

  Separating variables and integrating leads to $\frac{y^3}{3} = \frac{x^3}{3} + C$.
  Solving for the dependent  variable leads to $y = \sqrt[3]{x^3+3C}$.
:::

::: {#exm-Separable-4}
  Solve the differential equation $\frac{dy}{dx} = -\frac{2x}{y}$.

  Separating variables and integrating leads to $\frac{y^2}{2} = -x^2 + C$,
  which is a family of ellipses.
:::

::: {#exm-FirstOrderLinear-1} 
Solve the differential equation
 $\frac{du}{dt} = 2 + 2u + t + tu$.

 Here $u$ is our dependent variable.  The equation is both linear and separable so  we may choose either method.
 \begin{align*}
   \frac{du}{dt} &= (2+t)(1+u) \\
   \int \frac{du}{1+u} &= \int (2+t) \, dt  \\
   \ln|1+u| &= 2t+\frac{t^2}{2} + C \\
   |1+u| &= A \exp(2t+\frac{t^2}{2}) \\
   u &= -1 \pm A \exp(2t+\frac{t^2}{2}) 
 \end{align*}
 Note the use of $\pm$ is not necessary.  Since $A$ could be positive  or negative.
 It just serves to remind us that
 integration of $1/(1+u)$ leads to two solutions.
::: 

::: {#exm-Separable-5} 
  Solve the  differential  equation $xy' + y = y^2$.
  This is nonlinear, due to the $y^2$  term.  It is separable.
  \begin{align*}
    \frac{1}{y^2-y} y' &= \frac{1}{x} \\
    \int \frac{dy}{y^2-y} &= \int \frac{dx}{x} \\
    \int \frac{1}{y-1} - \frac{1}{y} dy &= \int \frac{dx}{x} \\
     \ln|y-1| - \ln|y| &= \ln|x| + C \\
     \ln\frac{|y-1|}{|x||y|} &=  C \\
     \frac{|y-1|}{|x||y|} &=  A 
  \end{align*}
  there are in fact several solutions buried in this notation.  For example, 
  if $0< y < 1$, then 
     $\frac{|y-1|}{|x||y|} = \frac{1-y}{xy}$, and we find $1/y - 1 = A/x \rightarrow y = x/(A+x)$,
     $A>0$.
::: 
As a further exercise,  sketch a few sample solutions with $y< 0$, $0 < y < 1$ and $y>1$.


## Linear first order differential equations {#sec-1storder-linear}

Consider a differential equation of the form 
$y'(t) +p(t) y(t) = q(t)$
with initial data $y(t_0) = y_0$.
These can be integrated using an **integrating factor**.
The trick is to find a factor, $u$, which turns the left hand side of the equation into the derivative of something familiar.
We multiply both sides of the equation by $u$,
$$u(t)y'(t) +u(t)p(t) y(t) = u(t)q(t).$$
Notice that if we can choose $u$ so that $up = u'$, then the left hand side is the derivative of $uy$:
$$\left(uy\right)' = uy' +u' y = uy' +up y =  uq.$$
We can solve this with a single integration
\begin{gather}
	\frac{d}{dt}\left(u(t)y(t)\right) =  u(t)q(t) \\
	u(t)y(t) =  \int u(s)q(s) \, ds \\
	y(t) =  \frac{1}{u(t)} \int u(s)q(s)\, ds 
\end{gather}
There is an arbitrary constant resulting from in the integration of $uq$. 
We'll use use our initial conditions to determine that once we determined $u$.

Returning to $u'=pu$, the differential equation for $u$, we see it is separable and has solutions of the form
$u(t) = \exp(\int p)$.
To make the result more readable, define $P(t) = \int_{t_0}^t p(s) \, ds$ and take $u$ as $u(t) = \exp(P(t))$.
This is the solution that also satisfies $u(t_0)=1$, which is convenient.
Putting this together with our expression for $y$, we find, in terms of $P$,
$$y(t) = e^{-P(t)} \int e^{P(s)}q(s)\, ds$$
This is our general solution, since it still has the constant of integration hiding in the integral.
Applying the initial conditions we find
$$y(t) = e^{-P(t)} \left( y_0 + \int_{t_0}^t e^{P(s)}q(s)\, ds \right)$$

::: {.callout-warning}
I advise against memorizing this formula. Instead memorize the technique.  Applying the technique is often simpler than applying the formula,  and we'll extend the ideas behind the method later in the course.
:::

::: {#exm-linearode-2}
Solve the initial value problem $t^2y' + 2ty = \log t, \ y(1) = 2$.

You can probably guess the integrating factor by noticing the left hand side looks like the product rule applied to $t^2y$.  Specifically, 
\begin{align*}
		t^2y' + 2ty &= \log t \\
		\dfrac{d}{dt}\left(t^2y\right)  &= \log t \\
		\left. s^2y(s) \right|_{s=1}^{s=t}  &= \int_1^t \log s \, ds \\
		t^2y(t) - y(1)  &= t\log(t) - t + 1 \\
		y(t) &= \frac{1}{t} \log(t) - \frac{1}{t} + \frac{3}{t^2}    
\end{align*}
:::

::: {.callout-tip}

If you don't immediately recognize the integrating factor, first rewrite the problem as
$y' + \dfrac{2}{t} y = \frac{1}{t^2}\log t$
The integrating factor can be computed as
$u(t) = \exp\left(\displaystyle\int \frac{2}{t} \, dt\right) = t^2$

:::


## Exercises {#sec-1storder-exr}

You should be familiar with material on basic differential equations in [Chapter 4 of OpenStax Calculus Volume 2](https://openstax.org/books/calculus-volume-2/pages/4-introduction), especially problems 119-142 in [Section 4.2](https://openstax.org/books/calculus-volume-2/pages/4-3-separable-equations)
and problems 208-250 and 257-261 in [Section 4.4](https://openstax.org/books/calculus-volume-2/pages/4-5-first-order-linear-equations).

::: {#exr-1storder-1}

Solve the initial value problem $x^2y' = (2+x)y$ with $y(1)=1$.

:::

::: {.callout-solution collapse=true}

- separate and integrate
\begin{align*}
  x^2y' &= (2+x)y \\
  \frac{y'}{y} &= \frac{2}{x^2}+\frac{1}{x} \\
  \int \frac{y'}{y} \, dx &= \int \frac{2}{x^2} \, dx +\int \frac{1}{x}  \, dx \\
  \log y &= -\frac{2}{x} + \log x + C \\
\end{align*}
- apply initial conditions by substituting 1 for $x$ and $y$
  $$\log 1 = -\frac{2}{1} + \log 1 + C \Rightarrow C = 2$$ 
- solve relation for $y$ in terms of $x$
\begin{align*}
  y(x) &= \exp\left(-\frac{2}{x} + \log x + 2\right) \\
       &= x\exp\left(2-\frac{2}{x}\right)
\end{align*}
:::

::: {#exr-1storder-2}

:::

::: {.callout-solution collapse=true}

:::
