---
author: James  Watmough
date: "`r Sys.Date()`"
---

{{< include texmacros.qmd >}}


# Introduction {#sec-intro}

## Motivating examples

The art of applied mathematics involves distilling a description of the state a system into relationships between variables.
For example,  consider a simple pendulum consisting of a mass on a rigid rod constrained to swing in a plane.
The various quantities of interest are the mass, $m$, the length of the rod, $l$, the horizontal displacement, $x$, the vertical displacement, $y$, both measured, for example, relative to the fixed end of the rod, and the angle of displacement, $\theta$.
These quantities are not independent.  We know $x^2+y^2 = l^2$, and we can choose to measure angle so that $x = \sin \theta$ and $y = \cos \theta$.
Our description so far is static, and our equations are algebraic.  

To describe the dynamics of the pendulum, we need to extend our mathematical description to include velocities, accelerations, forces and energies.
If we neglect the mass of the rod, we can hypothesize that the component of the gravitational force perpendicular to the rod acts to accelerate the mass radially.
$$\text{mass}\times\text{radial acceleration} = \text{radial force of gravity}$$
$$ml\ddot{\theta} = - m g \sin \theta$$ {#eq-nonlinear-pendulum}
Here $g$ denotes the gravitational constant and we use the double dot notation to denote the second derivative with respect to time.
If we assume the angle is small, we can approximate $\sin \theta$ by $\theta$ and Equation [@eq-nonlinear-pendulum] simplifies to
$$ml\ddot{\theta} = - m g \theta$$ {#eq-linear-pendulum}

Our goal in this course is to understand differential equations like [@eq-linear-pendulum].
We'll proceed more or less in the following order.

1. We'll start with simpler **first order** differential equations, some of which you'll have seen in your Calculus courses.  
2. Next we'll look at higher order differential equations and systems of first order differential equations. 
3. Most of our focus will be on **linear** differential equations and **initial value problems**. 
4. We'll use **Laplace transforms** to handle impulsive systems, like circuits with switches.
5. We'll briefly look at **Fourier series** and **boundary value problems**.

::: {#exm-intro-spring}
The motion of a mass on a spring is modelled as a balance of potential energy, $\frac{1}{2}kx^2$,  which is assumed proportional to the mass's squared displacement from an equilibrium position, and kinetic energy, $\frac{1}{2}m\dot{x}^2$ which is assumed proportional to the mass's squared velocity, or squared rate of change of displacement.  
Conservation of energy implies the sum of these two quantities remains constant.
You may have seen this expressed in terms of forces:  $m\ddot{x} + kx = 0$.   
Here the displacement, $x$, is our **dependent variable**.  The **independent variable**, time, is implicit.  We will refer to the mass, $m$, and the spring constant $k$ as our parameters.    The differential equation is often accompanied by **initial conditions**.  For example releasing the mass from rest with an initial displacement $x_0$ translates to the conditions $x(0) = x_0$, $\dot{x}(0) = 0$.
:::

::: {#exm-intro-logistic}
Exponential growth is modelled as a solution to the simple ode $y' = ry$.  More complex logistic growth is the solution to the equation $y' = ry(1-y/K)$.

:::

::: {#exm-intro-circuit}
Conservation of charge in an electrical circuit can be modelled as constraints between voltage drops, currents and their rates of change.
::: 

An ordinary differential equation is simply an equation involving an independent variable, say $t$, a dependant variable, $y$, and its derivatives, 
$\frac{dy}{dt}, \frac{d^2y}{dt^2}, \frac{d^3y}{dt^3}, \dots$   The order of a differential equation refers to the highest derivative present.
For example,  $$\frac{dy}{dt} = a\sin(bt)y(1-y)$$ is a first order nonlinear ordinary differential equation;
$$m\frac{d^2y}{dt^2} + r\frac{dy}{dt} + ky = a\cos(t)$$ is a second order linear differential equation.  The term **linear** refers to the linear dependence of the equation on the dependant variable and its derivatives.

A differential equation, or a system of differential equations is said to be linear if it is linear in the dependent variable(s) and their derivatives.   Thus,  the equation governing the motion of a damped oscillator subject to an external force $F$, $my'' - cy' + ky = F(t)$, is a linear second order differential equation, even if the forcing term $F$ is nonlinear in the independent variable $t$.

## Linear Differential Equations {#sec-intro-linear}

The main focus of this course is on linear ordinary differential equations.  This is for two simple reasons: (1) the mathematical theory for nonlinear equations is built on the simpler, more complete theory for linear equations, and (2) important concepts, such as system stability and responses to perturbations, are based on linear approximations to nonlinear equations.  For example,  a balance of forces acting on a mass swinging on a string (a pendulum) leads to the nonlinear differential equation
$$l\theta''(t) + g\sin \theta(t) = 0,$$
where $\theta(t)$ is the angular displacement of the mass at time $t$, $l$ is the string length and $g$ is our gravitational acceleration.  You should quickly verify that the constant function $\theta(t) = 0$ for all $t$ is a solution to the equation.  If the initial displacement is small, we expect the angle to stay close to zero.  Thus we approximate the nonlinear term, $g\sin(\theta)$, by its tangent line, $g\theta$, resulting in the more familiar linear differential equation
$$l\theta''(t) + g\theta(t) = 0.$$
This one we can solve almost by inspection, since we know that sine and cosine functions behave this way.  Indeed,  if we guess that $\theta(t) = \sin(\omega t)$ we can find the frequency, $\omega$, with some simple algebra:
\begin{align*}
	l\theta''(t) + g\theta(t) &= 0 \\
	l\frac{d^2}{d\theta^2}\sin(\omega t) + g\sin(\omega t) &= 0 \\
	-l\omega^2\sin(\omega t) + g\sin(\omega t) &= 0 \\
	\left(-l\omega^2 + g\right)\sin(\omega t)  &= 0 
\end{align*}
Thus either $\sin(\omega t) =0$ for all $t$, implying $\omega = 0$, or $\omega = \sqrt{g/l}$.  The first case is the trivial zero solution we already guessed,  the second case is the natural frequency of the pendulum.  We will cover this in more depth later.

## Higher order differential equations and systems of differential equations {#sec-intro-systems}

An $n^{\text{th}}$ order differential equation can be written
$${\cal{F}}\left(t,x,\frac{dx}{dt},\dots,\frac{d^nx}{dt^n}\right) = 0,$$
or if we solve for the highest derivative, 
$$\frac{d^nx}{dt^n} = F(t,x,\frac{dx}{dt},\dots,\frac{d^i_{n-1}x}{dt^{n-1}}).$$
Such an equation can also be written as a system of first order equations by introducing 
new dependent variables for the derivatives:
\begin{align*}
  x'_0 &= x_1,  \\
  x'_1 &= x_2,  \\
  x'_2 &= x_3,  \\
	x'_{n-1} &=  F(t,x_0,x_1,\dots,x_{n-1}).
\end{align*}
Here, $x_i$ is the $i^{\text{th}}$ derivative of $x$, and $x_0$ is our new name for the original variable.
Since higher order equations can be cast as systems of first order equations,  we will spend much of the course dealing with such systems.  Notationally,  we just allow the dependent variable to be a vector:
$x' = f(t,x)$, where $f:\R\times\R^n\to \R^n$.

Geometrically, the solution to a system of first order equations,  $x(t)$, describes a curve in $\R^n$ parameterized by $t$.  The
derivative $x'(t)$ is the vector tangent to this curve at $(t,x(t))$.  Hence,  the solution to the differential equation is
the curve $x(t)$, which is everywhere tangent to $f(t,x(t))$.

